### PR TITLE
[54] Added tests for GameController and InitController

### PR DESCRIPTION
**Pull request by NeverSoGoodStart**
- Added a few test configuration files, copied from Monopoly, including:
  - "chance" csv
  - "chest" csv
  - "properties" csv
  - "extra blocks" csv
- Added tests for GameController and InitController
- Modified some init logic in `Player`, removed some checks for `null`. I realized that some of the checks for `null` can just be replaced by setting some empty value directly, as the `Player` class should initialize with some empty attributes (instead of `null`) to satisfy the type annotation. 
- Wrote Javadocs for all the tests I wrote

### CODE REVIEW

**Comment by NeverSoGoodStart** [comment]
Regarding the tests for `main`, I haven't thought of any way to write an automated test for it at the moment. 
This is because, at the moment, most of the game is operating in a text-based envionment, with some RNG invovled. 
Therefore, it is a little bit hard to obtain information of the game. 

I can try obtaining `GameData` and play a few rounds, then test if the values differ from the initial values, does that sound like a good way to test it?

**Comment by Noahkong12** [comment]
Sounds good. We can also wait until we come up with more detailed CSV files for game info, then we can test again.

**Comment by NeverSoGoodStart** [comment]
> Sounds good. We can also wait until we come up with more detailed CSV files for game info, then we can test again.

Do I want to test for `main` here? I can try doing the following: 

> I can try obtaining GameData and play a few rounds, then test if the values differ from the initial values, does that sound like a good way to test it?

But do we want to wait until a more refined CSV is provided, then use that instead?

**Review by AlwynYin — DISMISSED** [review]

**Comment by duduGrassUoft** [comment]
> A reminder here, I'm currently making changes in GameController that might affect testing (I'm trying to retain its original function)

Well, turns out that I only have to change classes in the use case layer (for the newer version). snowQingYang has did some really good refactoring.

**Comment by duduGrassUoft** [comment]
But I recommend you to wait for the refactorized OwnerPropertyUseCases to be merged in order to double check if the property tests are compatible.

**Comment by snow-QingYang** [comment]
> But I recommend you to wait for the refactorized OwnerPropertyUseCases to be merged in order to double check if the property tests are compatible.

yea, we need to double check if the tests are compatible

**Review by hecateli — APPROVED** [review]

**Review by AlwynYin — APPROVED** [review]

**Pull request merged**
