### PR TITLE
[Enhancement] Fixing clean architecture issues for destiny block

### PR DESCRIPTION
**Pull request by hecateli**
Description: This PR fixes the clean architecture issues raised by issue: #12 #37 

- [x] Unit tests (Report test coverage of the project before and after the PR changes)
- before: there is no test for any files related to the destiny block functions
- after: all classes and methods are covered
`DestinyCardChooser`: Class **100%**, Method **100%**, Line **100%**
`DestinyCardExecutor`: Class **100%**, Method **100%**, Line **100%**
`DestinyCardPoolGenerator`: Class **100%**, Method **100%**, Line **92%**
`DestinyCard`: Class **100%**, Method **100%**, Line **100%**
`Destiny`: Class **100%**, Method **100%**, Line **100%**
- [x] Exception Handling
Add necessary exception handlings for majority classes
`DestinyCardExecutor`: NullPointerException, IllegalArgumentException
`DestinyCardPoolGenerator`: NullPointerException, IllegalArgumentException, NumberFormatException, FileNotFoundException, IOException

- [x] JavaDocs Documentation
Add JavaDocs to all classes and methods including test classes

- [x] SOLID principles

- SRP: All the classes are responsible for only one function
- Do not violate other principles

- [x] Clean Architecture
- [x] Design Pattern
`Destiny`: Use Dependency Injection design pattern - use `DestinyCardPoolGenerator` to generate DestinyCardPool instead of generating inside the class

### CODE REVIEW

**Comment by AlwynYin** [comment]
Should we also change the package UI to ui?

**Comment by hecateli** [comment]
I think UI is ok since it is an acronym. Or we can change it to "presenter"

**Review by duduGrassUoft — APPROVED** [review]

**Comment by hecateli** [comment]
Does anyone have ideas on testing the IOExcetion?

**Comment by AlwynYin** [comment]
> 

I don't think that's something we need to test because it is usually due to filesystem

**Review by AlwynYin — APPROVED** [review]

**Review by duduGrassUoft — APPROVED** [review]

**Review by Noahkong12 — APPROVED** [review]
This is a lot of work! Thanks for the commitment. I will look into it tmr morning.

**Pull request merged**
